using NuGetGuard.Models;

namespace NuGetGuard.Services;

/// <summary>
/// Static knowledge base: well-known package → SPDX license mappings (for packages that
/// ship no licenseExpression), license risk classification and licenseUrl → SPDX patterns.
/// </summary>
public static class LicenseCatalog
{
    private static readonly Dictionary<string, string> KnownPackageLicenses = new(StringComparer.OrdinalIgnoreCase)
    {
        // ── Microsoft / ASP.NET / .NET ────────────────────────────
        ["microsoft.aspnet.mvc"] = "Apache-2.0",
        ["microsoft.aspnet.razor"] = "Apache-2.0",
        ["microsoft.aspnet.webpages"] = "Apache-2.0",
        ["microsoft.aspnet.webpages.data"] = "Apache-2.0",
        ["microsoft.aspnet.webpages.oauth"] = "Apache-2.0",
        ["microsoft.aspnet.webapi"] = "Apache-2.0",
        ["microsoft.aspnet.webapi.client"] = "Apache-2.0",
        ["microsoft.aspnet.webapi.core"] = "Apache-2.0",
        ["microsoft.aspnet.webapi.owin"] = "Apache-2.0",
        ["microsoft.aspnet.webapi.tracing"] = "Apache-2.0",
        ["microsoft.aspnet.webapi.webhost"] = "Apache-2.0",
        ["microsoft.aspnet.web.optimization"] = "Apache-2.0",
        ["microsoft.aspnet.identity.core"] = "Apache-2.0",
        ["microsoft.aspnet.identity.entityframework"] = "Apache-2.0",
        ["microsoft.aspnet.identity.owin"] = "Apache-2.0",
        ["microsoft.aspnet.signalr"] = "Apache-2.0",
        ["microsoft.aspnet.signalr.core"] = "Apache-2.0",
        ["microsoft.aspnet.signalr.js"] = "Apache-2.0",
        ["microsoft.aspnet.signalr.systemweb"] = "Apache-2.0",
        ["microsoft.owin"] = "Apache-2.0",
        ["microsoft.owin.cors"] = "Apache-2.0",
        ["microsoft.owin.host.systemweb"] = "Apache-2.0",
        ["microsoft.owin.security"] = "Apache-2.0",
        ["microsoft.owin.security.cookies"] = "Apache-2.0",
        ["microsoft.owin.security.facebook"] = "Apache-2.0",
        ["microsoft.owin.security.google"] = "Apache-2.0",
        ["microsoft.owin.security.jwt"] = "Apache-2.0",
        ["microsoft.owin.security.microsoftaccount"] = "Apache-2.0",
        ["microsoft.owin.security.oauth"] = "Apache-2.0",
        ["microsoft.owin.security.twitter"] = "Apache-2.0",
        ["microsoft.owin.testing"] = "Apache-2.0",
        ["owin"] = "Apache-2.0",
        // ── Microsoft general packages ────────────────────────────
        ["microsoft.net.http"] = "MIT",
        ["microsoft.bcl"] = "MIT",
        ["microsoft.bcl.build"] = "MIT",
        ["microsoft.bcl.async"] = "MIT",
        ["microsoft.bcl.asyncinterfaces"] = "MIT",
        ["microsoft.csharp"] = "MIT",
        ["microsoft.codedom.providers.dotnetcompilerplatform"] = "MIT",
        // Ships the Microsoft .NET Library terms as its licence file, not an open-source licence
        ["microsoft.web.infrastructure"] = "MS-EULA",
        ["microsoft.extensions.caching.abstractions"] = "MIT",
        ["microsoft.extensions.caching.memory"] = "MIT",
        ["microsoft.extensions.configuration"] = "MIT",
        ["microsoft.extensions.configuration.abstractions"] = "MIT",
        ["microsoft.extensions.configuration.binder"] = "MIT",
        ["microsoft.extensions.configuration.commandline"] = "MIT",
        ["microsoft.extensions.configuration.environmentvariables"] = "MIT",
        ["microsoft.extensions.configuration.json"] = "MIT",
        ["microsoft.extensions.configuration.xml"] = "MIT",
        ["microsoft.extensions.dependencyinjection"] = "MIT",
        ["microsoft.extensions.dependencyinjection.abstractions"] = "MIT",
        ["microsoft.extensions.diagnostics.abstractions"] = "MIT",
        ["microsoft.extensions.fileproviders.abstractions"] = "MIT",
        ["microsoft.extensions.fileproviders.composite"] = "MIT",
        ["microsoft.extensions.fileproviders.physical"] = "MIT",
        ["microsoft.extensions.filesystemglobbing"] = "MIT",
        ["microsoft.extensions.hosting"] = "MIT",
        ["microsoft.extensions.hosting.abstractions"] = "MIT",
        ["microsoft.extensions.http"] = "MIT",
        ["microsoft.extensions.logging"] = "MIT",
        ["microsoft.extensions.logging.abstractions"] = "MIT",
        ["microsoft.extensions.logging.configuration"] = "MIT",
        ["microsoft.extensions.logging.console"] = "MIT",
        ["microsoft.extensions.logging.debug"] = "MIT",
        ["microsoft.extensions.logging.eventlog"] = "MIT",
        ["microsoft.extensions.logging.eventsource"] = "MIT",
        ["microsoft.extensions.options"] = "MIT",
        ["microsoft.extensions.options.configurationextensions"] = "MIT",
        ["microsoft.extensions.primitives"] = "MIT",
        ["microsoft.extensions.objectpool"] = "MIT",
        ["microsoft.extensions.webencoding"] = "MIT",
        ["entityframework"] = "MIT",
        ["entityframework.sqlserver"] = "MIT",
        ["entityframework.sqlservercompact"] = "MIT",
        ["microsoft.entityframeworkcore"] = "MIT",
        ["microsoft.entityframeworkcore.abstractions"] = "MIT",
        ["microsoft.entityframeworkcore.analyzers"] = "MIT",
        ["microsoft.entityframeworkcore.design"] = "MIT",
        ["microsoft.entityframeworkcore.inmemory"] = "MIT",
        ["microsoft.entityframeworkcore.relational"] = "MIT",
        ["microsoft.entityframeworkcore.sqlserver"] = "MIT",
        ["microsoft.entityframeworkcore.sqlite"] = "MIT",
        ["microsoft.entityframeworkcore.tools"] = "MIT",
        ["system.buffers"] = "MIT",
        ["system.collections"] = "MIT",
        ["system.collections.concurrent"] = "MIT",
        ["system.collections.immutable"] = "MIT",
        ["system.componentmodel.annotations"] = "MIT",
        ["system.componentmodel.composition"] = "MIT",
        ["system.data.common"] = "MIT",
        ["system.diagnostics.debug"] = "MIT",
        ["system.diagnostics.diagnosticsource"] = "MIT",
        ["system.diagnostics.tracing"] = "MIT",
        ["system.dynamic.runtime"] = "MIT",
        ["system.globalization"] = "MIT",
        ["system.io"] = "MIT",
        ["system.io.filesystem"] = "MIT",
        ["system.io.pipelines"] = "MIT",
        ["system.linq"] = "MIT",
        ["system.linq.expressions"] = "MIT",
        ["system.linq.queryable"] = "MIT",
        ["system.memory"] = "MIT",
        ["system.net.http"] = "MIT",
        ["system.net.primitives"] = "MIT",
        ["system.numerics.vectors"] = "MIT",
        ["system.objectmodel"] = "MIT",
        ["system.reflection"] = "MIT",
        ["system.reflection.emit"] = "MIT",
        ["system.reflection.extensions"] = "MIT",
        ["system.reflection.metadata"] = "MIT",
        ["system.reflection.primitives"] = "MIT",
        ["system.resources.resourcemanager"] = "MIT",
        ["system.runtime"] = "MIT",
        ["system.runtime.caching"] = "MIT",
        ["system.runtime.compilerservices.unsafe"] = "MIT",
        ["system.runtime.extensions"] = "MIT",
        ["system.runtime.handles"] = "MIT",
        ["system.runtime.interopservices"] = "MIT",
        ["system.runtime.interopservices.runtimeinformation"] = "MIT",
        ["system.runtime.numerics"] = "MIT",
        ["system.security.claims"] = "MIT",
        ["system.security.cryptography.algorithms"] = "MIT",
        ["system.security.cryptography.encoding"] = "MIT",
        ["system.security.cryptography.primitives"] = "MIT",
        ["system.security.cryptography.x509certificates"] = "MIT",
        ["system.security.permissions"] = "MIT",
        ["system.servicemodel.primitives"] = "MIT",
        ["system.text.encoding"] = "MIT",
        ["system.text.encoding.codepages"] = "MIT",
        ["system.text.encoding.extensions"] = "MIT",
        ["system.text.encodings.web"] = "MIT",
        ["system.text.regularexpressions"] = "MIT",
        ["system.threading"] = "MIT",
        ["system.threading.channels"] = "MIT",
        ["system.threading.tasks"] = "MIT",
        ["system.threading.tasks.dataflow"] = "MIT",
        ["system.threading.tasks.extensions"] = "MIT",
        ["system.threading.timer"] = "MIT",
        ["system.valuetuple"] = "MIT",
        ["system.xml.readerwriter"] = "MIT",
        ["system.xml.xdocument"] = "MIT",
        ["microsoft.identity.client"] = "MIT",
        ["microsoft.identity.web"] = "MIT",
        ["microsoft.identitymodel.clients.activedirectory"] = "MIT",
        ["microsoft.identitymodel.jsonwebtokens"] = "MIT",
        ["microsoft.identitymodel.logging"] = "MIT",
        ["microsoft.identitymodel.protocols"] = "MIT",
        ["microsoft.identitymodel.protocols.openidconnect"] = "MIT",
        ["microsoft.identitymodel.tokens"] = "MIT",
        ["system.identitymodel.tokens.jwt"] = "MIT",
        // ── NUnit / xUnit / testing ───────────────────────────────
        ["nunit"] = "MIT",
        ["nunit3testadapter"] = "MIT",
        ["nunitlite"] = "MIT",
        ["xunit"] = "Apache-2.0",
        ["xunit.core"] = "Apache-2.0",
        ["xunit.abstractions"] = "Apache-2.0",
        ["xunit.assert"] = "Apache-2.0",
        ["xunit.extensibility.core"] = "Apache-2.0",
        ["xunit.extensibility.execution"] = "Apache-2.0",
        ["xunit.runner.visualstudio"] = "Apache-2.0",
        ["microsoft.net.test.sdk"] = "MIT",
        ["microsoft.testplatform.testhost"] = "MIT",
        // Older MSTest releases only linked the .NET library EULA; the package is MIT
        ["mstest.testadapter"] = "MIT",
        ["mstest.testframework"] = "MIT",
        ["fluentassertions"] = "Apache-2.0",
        ["moq"] = "BSD-3-Clause",
        ["castle.core"] = "Apache-2.0",
        ["nsubstitute"] = "BSD-3-Clause",
        ["bogus"] = "MIT",
        ["fakeiteasly"] = "MIT",
        ["comparenetobjects"] = "MIT",
        // ── Logging ───────────────────────────────────────────────
        ["serilog"] = "Apache-2.0",
        ["serilog.aspnetcore"] = "Apache-2.0",
        ["serilog.enrichers.environment"] = "Apache-2.0",
        ["serilog.enrichers.process"] = "Apache-2.0",
        ["serilog.enrichers.thread"] = "Apache-2.0",
        ["serilog.extensions.hosting"] = "Apache-2.0",
        ["serilog.extensions.logging"] = "Apache-2.0",
        ["serilog.formatting.compact"] = "Apache-2.0",
        ["serilog.sinks.applicationinsights"] = "Apache-2.0",
        ["serilog.sinks.console"] = "Apache-2.0",
        ["serilog.sinks.debug"] = "Apache-2.0",
        ["serilog.sinks.elasticsearch"] = "Apache-2.0",
        ["serilog.sinks.file"] = "Apache-2.0",
        ["serilog.sinks.mssqlserver"] = "Apache-2.0",
        ["serilog.sinks.seq"] = "Apache-2.0",
        ["log4net"] = "Apache-2.0",
        ["nlog"] = "BSD-3-Clause",
        ["nlog.web.aspnetcore"] = "BSD-3-Clause",
        ["nlog.extensions.logging"] = "BSD-3-Clause",
        ["elmah"] = "Apache-2.0",
        // ── JSON / Serialization ──────────────────────────────────
        ["newtonsoft.json"] = "MIT",
        ["newtonsoft.json.schema"] = "MIT",
        ["messagepack"] = "MIT",
        ["messagepack.annotations"] = "MIT",
        ["protobuf-net"] = "Apache-2.0",
        ["protobuf-net.core"] = "Apache-2.0",
        ["google.protobuf"] = "BSD-3-Clause",
        ["apache.avro"] = "Apache-2.0",
        ["csvhelper"] = "MS-PL",
        ["tinyjson"] = "MIT",
        ["system.text.json"] = "MIT",
        // ── Database / ORM ────────────────────────────────────────
        ["dapper"] = "Apache-2.0",
        ["dapper.contrib"] = "Apache-2.0",
        ["nhibernate"] = "LGPL-2.1",
        ["fluent-nhibernate"] = "BSD-3-Clause",
        ["npgsql"] = "MIT",
        ["npgsql.entityframeworkcore.postgresql"] = "MIT",
        ["mongodb.driver"] = "Apache-2.0",
        ["mongodb.bson"] = "Apache-2.0",
        ["stackexchange.redis"] = "MIT",
        ["mysql.data"] = "GPL-2.0",
        ["mysqlconnector"] = "MIT",
        ["oracle.manageddataaccess"] = "Commercial",
        ["system.data.sqlite"] = "MS-PL",
        ["sqlite-net-pcl"] = "MIT",
        ["microsoft.data.sqlite"] = "MIT",
        ["microsoft.data.sqlite.core"] = "MIT",
        ["microsoft.data.sqlclient"] = "MIT",
        // The SNI packages ship the Microsoft .NET Library terms, not the MIT licence of the parent
        ["microsoft.sqlserver.sqlmanagementobjects"] = "MIT",
        ["system.data.sqlclient"] = "MIT",
        ["linq2db"] = "MIT",
        ["linq2db.sqlite"] = "MIT",
        ["linq2db.sqlserver"] = "MIT",
        ["marten"] = "MIT",
        ["realm"] = "Apache-2.0",
        // ── HTTP / REST ───────────────────────────────────────────
        ["restsharp"] = "Apache-2.0",
        ["flurl"] = "MIT",
        ["flurl.http"] = "MIT",
        ["refit"] = "MIT",
        ["polly"] = "BSD-3-Clause",
        ["polly.extensions.http"] = "BSD-3-Clause",
        ["httpclientfactory"] = "MIT",
        ["odata.core"] = "MIT",
        // ── Mapping ───────────────────────────────────────────────
        ["automapper"] = "MIT",
        ["automapper.extensions.microsoft.dependencyinjection"] = "MIT",
        ["mapster"] = "MIT",
        ["tinymapper"] = "MIT",
        // ── Validation ────────────────────────────────────────────
        ["fluentvalidation"] = "Apache-2.0",
        ["fluentvalidation.aspnetcore"] = "Apache-2.0",
        ["fluentvalidation.dependencyinjectionextensions"] = "Apache-2.0",
        ["jquery.validation"] = "MIT",
        ["jquery.validation.unobtrusive"] = "MIT",
        // Old releases link to a Microsoft EULA; version 4 declares MIT, as does the source repository
        ["microsoft.jquery.unobtrusive.validation"] = "MIT",
        ["microsoft.jquery.unobtrusive.ajax"] = "MIT",
        ["modernizr"] = "MIT",
        ["popper.js"] = "MIT",
        ["jquery"] = "MIT",
        ["jquery.ui.combined"] = "MIT",
        ["jquery.datatables"] = "MIT",
        // ── MediatR / CQRS / messaging ────────────────────────────
        ["mediatr"] = "Apache-2.0",
        ["mediatr.extensions.microsoft.dependencyinjection"] = "Apache-2.0",
        ["masstransit"] = "Apache-2.0",
        ["masstransit.rabbitmq"] = "Apache-2.0",
        ["masstransit.azure.servicebus.core"] = "Apache-2.0",
        ["nservicebus"] = "Commercial",
        ["rebus"] = "MIT",
        // ── AWS ───────────────────────────────────────────────────
        ["awssdk.core"] = "Apache-2.0",
        ["awssdk.s3"] = "Apache-2.0",
        ["awssdk.sqs"] = "Apache-2.0",
        ["awssdk.sns"] = "Apache-2.0",
        ["awssdk.dynamodbv2"] = "Apache-2.0",
        ["awssdk.lambda"] = "Apache-2.0",
        ["awssdk.secretsmanager"] = "Apache-2.0",
        ["awssdk.securitytoken"] = "Apache-2.0",
        ["awssdk.cognitoidentityprovider"] = "Apache-2.0",
        ["awssdk.cloudwatch"] = "Apache-2.0",
        ["awssdk.cloudwatchlogs"] = "Apache-2.0",
        // ── Azure ─────────────────────────────────────────────────
        ["azure.core"] = "MIT",
        ["azure.storage.blobs"] = "MIT",
        ["azure.storage.queues"] = "MIT",
        ["azure.storage.files.shares"] = "MIT",
        ["azure.messaging.servicebus"] = "MIT",
        ["azure.messaging.eventhubs"] = "MIT",
        ["azure.keyvault.secrets"] = "MIT",
        ["azure.identity"] = "MIT",
        ["azure.security.keyvault.secrets"] = "MIT",
        ["microsoft.azure.servicebus"] = "MIT",
        ["microsoft.azure.eventhubs"] = "MIT",
        ["microsoft.azure.storage.blob"] = "MIT",
        ["microsoft.azure.storage.queue"] = "MIT",
        ["microsoft.azure.webjobs"] = "MIT",
        ["microsoft.azure.functions.extensions"] = "MIT",
        ["microsoft.azure.appservice.proxy"] = "MIT",
        ["windowsazure.storage"] = "Apache-2.0",
        // ── Dependency Injection ──────────────────────────────────
        ["autofac"] = "MIT",
        ["autofac.extensions.dependencyinjection"] = "MIT",
        ["ninject"] = "Apache-2.0",
        ["simpleinjector"] = "MIT",
        ["lamar"] = "MIT",
        ["structuremap"] = "Apache-2.0",
        ["unity"] = "Apache-2.0",
        ["unity.container"] = "Apache-2.0",
        ["dryloc.dll"] = "MIT",
        ["lightinject"] = "MIT",
        // ── Utilities ─────────────────────────────────────────────
        ["humanizer"] = "MIT",
        ["humanizer.core"] = "MIT",
        ["noda time"] = "Apache-2.0",
        ["nodatime"] = "Apache-2.0",
        ["cronexpressiondescriptor"] = "MIT",
        ["ncrontab"] = "Apache-2.0",
        ["hangfire"] = "LGPL-3.0",
        ["hangfire.core"] = "LGPL-3.0",
        ["hangfire.aspnetcore"] = "LGPL-3.0",
        ["hangfire.sqlserver"] = "LGPL-3.0",
        ["quartz"] = "Apache-2.0",
        ["quartz.net"] = "Apache-2.0",
        ["coravel"] = "MIT",
        ["ipnetwork2"] = "BSD-2-Clause",
        ["handlebar.net"] = "MIT",
        ["handlebars.net"] = "MIT",
        ["scriban"] = "BSD-2-Clause",
        ["fluid.core"] = "MIT",
        ["dotliquid"] = "Apache-2.0",
        ["markdig"] = "BSD-2-Clause",
        ["commonmark.net"] = "BSD-3-Clause",
        ["yaml-dotnet"] = "MIT",
        ["yamldotnet"] = "MIT",
        ["iron.python"] = "Apache-2.0",
        ["ironpython"] = "Apache-2.0",
        ["fody"] = "MIT",
        ["propertychanged.fody"] = "MIT",
        ["methoddecorator.fody"] = "MIT",
        ["antlr4.runtime.standard"] = "BSD-3-Clause",
        ["antlr"] = "BSD-3-Clause",
        ["antlr4"] = "BSD-3-Clause",
        // ── File / Document ───────────────────────────────────────
        ["7zsharp"] = "LGPL-2.1",
        ["7z.libs"] = "LGPL-2.1",
        ["dotnetzip"] = "MS-PL",
        ["sharpziplib"] = "MIT",
        ["ionmezle.sharpziplib"] = "MIT",
        ["closedxml"] = "MIT",
        ["documentformat.openxml"] = "MIT",
        ["epplus"] = "LGPL-3.0",
        ["epplus.interfaces"] = "LGPL-3.0",
        ["exceldatareader"] = "MIT",
        ["exceldatareader.dataset"] = "MIT",
        ["itextsharp"] = "AGPL-3.0",
        ["itext7"] = "AGPL-3.0",
        ["itext7.bouncy-castle-adapter"] = "AGPL-3.0",
        ["pdfsharp"] = "MIT",
        ["pdfsharp-wpf"] = "MIT",
        ["dinktohtml"] = "MIT",
        ["dinktohtml.native.osx"] = "MIT",
        ["dinktohtml.native.linux"] = "MIT",
        ["dinktohtml.native.windows"] = "MIT",
        ["wkhtmltopdf-dotnet"] = "MIT",
        ["ghostscript.net"] = "AGPL-3.0",
        ["edtftpnet"] = "MIT",
        ["edtftpnet-pro"] = "Commercial",
        ["fluentstorage"] = "MIT",
        ["ckeditor"] = "GPL-2.0",
        ["ckeditor-full"] = "GPL-2.0",
        ["chosen"] = "MIT",
        ["chosen.jquery"] = "MIT",
        // ── Imaging ───────────────────────────────────────────────
        ["imagesharp"] = "Apache-2.0",
        ["sixlabors.imagesharp"] = "Apache-2.0",
        ["sixlabors.imagesharp.web"] = "Apache-2.0",
        ["skiasharp"] = "MIT",
        ["magick.net-q16-anycpu"] = "Apache-2.0",
        ["magick.net-q8-anycpu"] = "Apache-2.0",
        ["imageresizer"] = "Apache-2.0",
        ["dotnetopenauth.core"] = "MS-PL",
        ["dotnetopenauth.aspnet"] = "MS-PL",
        // ── Selenium / UI testing ─────────────────────────────────
        ["selenium.webdriver"] = "Apache-2.0",
        ["selenium.webdriver.chromedriver"] = "Apache-2.0",
        ["selenium.webdriver.firefoxdriver"] = "Apache-2.0",
        ["selenium.support"] = "Apache-2.0",
        ["dotnetseleniumextras.waithelpers"] = "Apache-2.0",
        ["dotnetseleniumextras.pageobjects"] = "Apache-2.0",
        ["playwright"] = "MIT",
        ["microsoft.playwright"] = "MIT",
        // ── gRPC ──────────────────────────────────────────────────
        ["grpc"] = "Apache-2.0",
        ["grpc.tools"] = "Apache-2.0",
        ["grpc.aspnetcore"] = "Apache-2.0",
        ["grpc.net.client"] = "Apache-2.0",
        ["grpc.net.clientfactory"] = "Apache-2.0",
        ["google.api.commonprotos"] = "Apache-2.0",
        // ── Messaging / queues ────────────────────────────────────
        ["easynetq"] = "MIT",
        ["rabbitmq.client"] = "Apache-2.0",
        ["confluent.kafka"] = "Apache-2.0",
        ["confluent.schemaregistry"] = "Apache-2.0",
        // ── Security / Crypto ─────────────────────────────────────
        ["bouncycastle.cryptography"] = "MIT",
        ["bouncycastle"] = "MIT",
        ["jose-jwt"] = "MIT",
        ["system.security.cryptography.protecteddata"] = "MIT",
        // ── Misc popular packages ─────────────────────────────────
        ["morelinq"] = "Apache-2.0",
        ["linq.extras"] = "MIT",
        ["z.extmethods"] = "MIT",
        ["z.expressions.eval"] = "MIT",
        ["linq2twitter"] = "MS-PL",
        ["twitterizer2"] = "BSD-3-Clause",
        ["tweetinvi"] = "MIT",
        ["mailkit"] = "MIT",
        ["mimekit"] = "MIT",
        ["fluentemail.core"] = "MIT",
        ["fluentemail.smtp"] = "MIT",
        ["twilio"] = "MIT",
        ["stripe.net"] = "Apache-2.0",
        ["braintree"] = "MIT",
        ["paypalcheckoutsdk"] = "Apache-2.0",
        ["smartformat.net"] = "MIT",
        ["pdfpig"] = "Apache-2.0",
        ["benchmark.net"] = "MIT",
        ["benchmarkdotnet"] = "MIT",
        ["nito.asyncex"] = "MIT",
        ["nito.asyncex.coordination"] = "MIT",
        ["nito.asyncex.tasks"] = "MIT",
        ["scrutor"] = "MIT",
        ["ardalis.result"] = "MIT",
        ["ardalis.smartenum"] = "MIT",
        ["ardalis.specification"] = "MIT",
        ["coverlet.collector"] = "MIT",
        ["microsoft.codecoverage"] = "MIT",
        ["opentelemetry"] = "Apache-2.0",
        ["opentelemetry.api"] = "Apache-2.0",
        ["opentelemetry.exporter.console"] = "Apache-2.0",
        ["opentelemetry.exporter.otlpexporter"] = "Apache-2.0",
        ["opentelemetry.extensions.hosting"] = "Apache-2.0",
        ["opentelemetry.instrumentation.aspnetcore"] = "Apache-2.0",
        ["opentelemetry.instrumentation.http"] = "Apache-2.0",
        ["prometheus-net"] = "MIT",
        ["prometheus-net.aspnetcore"] = "MIT",
        ["app-metrics-core"] = "Apache-2.0",
        ["healthchecks.ui"] = "Apache-2.0",
        ["healthchecks.sqlserver"] = "MIT",
        ["swashbuckle.aspnetcore"] = "MIT",
        ["swashbuckle.aspnetcore.swagger"] = "MIT",
        ["swashbuckle.aspnetcore.swaggergen"] = "MIT",
        ["swashbuckle.aspnetcore.swaggerui"] = "MIT",
        ["swashbuckle"] = "BSD-2-Clause",
        ["nswag.aspnetcore"] = "MIT",
        ["nswag.core"] = "MIT",
        ["microsoft.aspnetcore.openapi"] = "MIT",
        ["microsoft.aspnetcore.mvc.versioning"] = "MIT",
        ["asp.versioning.mvc"] = "MIT",
        ["asp.versioning.http"] = "MIT",
        ["specflow"] = "BSD-3-Clause",
        ["specflow.nunit"] = "BSD-3-Clause",
        ["specflow.xunit"] = "BSD-3-Clause",
        ["reqnroll"] = "BSD-3-Clause",
        ["telerik.justmock"] = "Commercial",
        ["wisej.net"] = "Commercial",
        ["devexpress"] = "Commercial",
        ["syncfusion"] = "Commercial",
        ["infragistics"] = "Commercial",
        ["componentone"] = "Commercial",
    };

    // Ordered: first matching prefix wins (covers Microsoft.AspNetCore.*, Azure.*, etc.)
    private static readonly (string Prefix, string License)[] PrefixMap =
    [
        ("microsoft.aspnetcore.", "MIT"),
        ("microsoft.aspnet.", "Apache-2.0"),
        ("microsoft.extensions.", "MIT"),
        ("microsoft.entityframeworkcore.", "MIT"),
        ("microsoft.azure.", "MIT"),
        ("microsoft.identity.", "MIT"),
        ("microsoft.identitymodel.", "MIT"),
        ("microsoft.net.", "MIT"),
        ("microsoft.netcore.", "MIT"),
        ("microsoft.visualstudio.", "MIT"),
        ("microsoft.codeanalysis.", "MIT"),
        ("microsoft.build.", "MIT"),
        ("system.", "MIT"),
        ("azure.", "MIT"),
        ("awssdk.", "Apache-2.0"),
        ("serilog.", "Apache-2.0"),
        ("nlog.", "BSD-3-Clause"),
        ("nunit.", "MIT"),
        ("xunit.", "Apache-2.0"),
        ("fluentvalidation.", "Apache-2.0"),
        ("fluentassertions.", "Apache-2.0"),
        ("automapper.", "MIT"),
        ("autofac.", "MIT"),
        ("mediatr.", "Apache-2.0"),
        ("masstransit.", "Apache-2.0"),
        ("hangfire.", "LGPL-3.0"),
        ("opentelemetry.", "Apache-2.0"),
        ("grpc.", "Apache-2.0"),
        ("sixlabors.", "Apache-2.0"),
        ("polly.", "BSD-3-Clause"),
        ("npgsql.", "MIT"),
        ("magick.net", "Apache-2.0"),
    ];

    private static readonly Dictionary<string, LicenseRisk> LicenseRiskMap = new(StringComparer.OrdinalIgnoreCase)
    {
        // Permissive (green)
        ["MIT"] = LicenseRisk.Permissive,
        ["Apache-2.0"] = LicenseRisk.Permissive,
        ["Apache 2.0"] = LicenseRisk.Permissive,
        ["BSD-2-Clause"] = LicenseRisk.Permissive,
        ["BSD-3-Clause"] = LicenseRisk.Permissive,
        ["ISC"] = LicenseRisk.Permissive,
        ["Unlicense"] = LicenseRisk.Permissive,
        ["CC0-1.0"] = LicenseRisk.Permissive,
        ["MS-PL"] = LicenseRisk.Permissive,
        ["WTFPL"] = LicenseRisk.Permissive,
        ["Zlib"] = LicenseRisk.Permissive,
        ["PSF-2.0"] = LicenseRisk.Permissive,
        ["0BSD"] = LicenseRisk.Permissive,
        ["BSL-1.0"] = LicenseRisk.Permissive,
        // Weak copyleft (yellow)
        ["LGPL-2.0"] = LicenseRisk.WeakCopyleft,
        ["LGPL-2.0-only"] = LicenseRisk.WeakCopyleft,
        ["LGPL-2.1"] = LicenseRisk.WeakCopyleft,
        ["LGPL-2.1-only"] = LicenseRisk.WeakCopyleft,
        ["LGPL-3.0"] = LicenseRisk.WeakCopyleft,
        ["LGPL-3.0-only"] = LicenseRisk.WeakCopyleft,
        ["MPL-2.0"] = LicenseRisk.WeakCopyleft,
        ["EUPL-1.1"] = LicenseRisk.WeakCopyleft,
        ["EUPL-1.2"] = LicenseRisk.WeakCopyleft,
        ["MS-RL"] = LicenseRisk.WeakCopyleft,
        ["CDDL-1.0"] = LicenseRisk.WeakCopyleft,
        ["EPL-1.0"] = LicenseRisk.WeakCopyleft,
        ["EPL-2.0"] = LicenseRisk.WeakCopyleft,
        // Strong copyleft (red)
        ["GPL-2.0"] = LicenseRisk.StrongCopyleft,
        ["GPL-2.0-only"] = LicenseRisk.StrongCopyleft,
        ["GPL-2.0-or-later"] = LicenseRisk.StrongCopyleft,
        ["GPL-3.0"] = LicenseRisk.StrongCopyleft,
        ["GPL-3.0-only"] = LicenseRisk.StrongCopyleft,
        ["GPL-3.0-or-later"] = LicenseRisk.StrongCopyleft,
        ["AGPL-3.0"] = LicenseRisk.StrongCopyleft,
        ["AGPL-3.0-only"] = LicenseRisk.StrongCopyleft,
        ["AGPL-3.0-or-later"] = LicenseRisk.StrongCopyleft,
        ["OSL-3.0"] = LicenseRisk.StrongCopyleft,
        ["CC-BY-SA-4.0"] = LicenseRisk.StrongCopyleft,
        ["CC-BY-NC-4.0"] = LicenseRisk.StrongCopyleft,
    };

    public static string? GetKnownLicense(string? packageId)
    {
        if (string.IsNullOrEmpty(packageId))
            return null;

        if (KnownPackageLicenses.TryGetValue(packageId, out var license))
            return license;

        foreach (var (prefix, prefixLicense) in PrefixMap)
        {
            if (packageId.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                return prefixLicense;
        }

        return null;
    }

    public static LicenseRisk GetRisk(string? license)
    {
        if (string.IsNullOrEmpty(license) || license == "Unknown")
            return LicenseRisk.Unknown;

        if (LicenseRiskMap.TryGetValue(license, out var risk))
            return risk;

        // Fuzzy match for compound expressions like "MIT OR Apache-2.0"
        if (license.Contains("GPL", StringComparison.OrdinalIgnoreCase) &&
            !license.Contains("LGPL", StringComparison.OrdinalIgnoreCase))
            return LicenseRisk.StrongCopyleft;
        if (license.Contains("LGPL", StringComparison.OrdinalIgnoreCase))
            return LicenseRisk.WeakCopyleft;
        if (license.Contains("MPL", StringComparison.OrdinalIgnoreCase) ||
            license.Contains("EPL", StringComparison.OrdinalIgnoreCase) ||
            license.Contains("EUPL", StringComparison.OrdinalIgnoreCase) ||
            license.Contains("CDDL", StringComparison.OrdinalIgnoreCase))
            return LicenseRisk.WeakCopyleft;
        if (license.Contains("MIT", StringComparison.OrdinalIgnoreCase) ||
            license.Contains("Apache", StringComparison.OrdinalIgnoreCase) ||
            license.Contains("BSD", StringComparison.OrdinalIgnoreCase) ||
            license.Contains("ISC", StringComparison.OrdinalIgnoreCase) ||
            license.Contains("Unlicense", StringComparison.OrdinalIgnoreCase) ||
            license.Contains("Ms-PL", StringComparison.OrdinalIgnoreCase))
            return LicenseRisk.Permissive;

        return LicenseRisk.Unknown;
    }
}
